spring:
  datasource:
    url: jdbc:mysql://localhost:3306/infytel_customer
    
feign:
  client:
    plan-service-url: http://localhost:8082
   # friendfamily-service-url: http://localhost:8084
    
friendfamilyServiceClient:
  ribbon:
    listOfServers: http://localhost:8084, http://localhost:8085
