spring:
  datasource:
    url: jdbc:mysql://localhost:3306/infytel_customer
    
client:
    plan-service-url: http://localhost:8082/plan
    friendfamily-service-url: http://localhost:8084
    
customerRibbon:
  ribbon:
    eureka:
      enabled: false
      
    listOfServers: http://localhost:8084,http://localhost:8085   
